# Generated by Django 6.0.2 on 2026-02-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_encounter_clinic_alter_encounter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='anamnesis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='prescription',
            field=models.TextField(blank=True),
        ),
    ]
