# Generated by Django 6.0.2 on 2026-02-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_anamnesis_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
