# Generated by Django 6.0.2 on 2026-02-12 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_audit_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='reason',
        ),
    ]
